FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "Hirovo.sln"
RUN dotnet publish "BusinessModules/AnimalMarket/BusinessModules.AnimalMarket.Workers/MailSender/BusinessModules.AnimalMarket.Workers.MailSender.csproj" \
    -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BusinessModules.AnimalMarket.Workers.MailSender.dll"]
