FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "Hirovo.sln"
RUN dotnet publish "BusinessModules/Hirovo/BusinessModules.Hirovo.Workers/SmsSender/BusinessModules.Hirovo.Workers.SmsSender.csproj" \
    -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BusinessModules.Hirovo.Workers.SmsSender.dll"]
