FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "Hirovo.sln"
RUN dotnet publish "BaseModules/IAM/BaseModules.IAM.Workers/MailSender/BaseModules.IAM.Workers.MailSender.csproj" \
    -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BaseModules.IAM.Workers.MailSender.dll"]
