<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>LivestockTrading.Messaging.Domain</RootNamespace>
    <AssemblyName>LivestockTrading.Messaging.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\LivestockTrading.Shared.Kernel\LivestockTrading.Shared.Kernel.csproj" />
  </ItemGroup>

</Project>
