
# Direct API
@Url = http://localhost:5000

# Gateway
# @Url = http://localhost:8080/keepzo/api/keepzo

@LicenseKey = YOUR_LICENSE_KEY_HERE
@JobId = 00000000-0000-0000-0000-000000000000

###############################################
# BACKUP JOBS - Commands
###############################################

### Start Backup Job
# Yeni bir backup job baslatir
POST {{Url}}/BackupJobs/Start
Accept: application/json
Content-Type: application/json

{
  "licenseKey": "{{LicenseKey}}",
  "deviceId": "device-001",
  "deviceName": "MyPC",
  "backupType": 0,
  "estimatedFileCount": 100,
  "estimatedTotalBytes": 1073741824
}

# backupType:
# 0 = Full
# 1 = Incremental
# 2 = Differential


### Complete Backup Job
# Backup job'i tamamlar
POST {{Url}}/BackupJobs/Complete
Accept: application/json
Content-Type: application/json

{
  "licenseKey": "{{LicenseKey}}",
  "jobId": "{{JobId}}",
  "success": true,
  "errorMessage": null,
  "totalFiles": 100,
  "totalBytes": 1073741824,
  "processedFiles": 98,
  "processedBytes": 1050000000,
  "failedFiles": 2,
  "skippedFiles": 0
}


### Complete Backup Job - With Error
# Hata ile backup job'i tamamlar
POST {{Url}}/BackupJobs/Complete
Accept: application/json
Content-Type: application/json

{
  "licenseKey": "{{LicenseKey}}",
  "jobId": "{{JobId}}",
  "success": false,
  "errorMessage": "Disk space insufficient",
  "totalFiles": 100,
  "totalBytes": 1073741824,
  "processedFiles": 50,
  "processedBytes": 500000000,
  "failedFiles": 50,
  "skippedFiles": 0
}
