using System.Text.Json;
using Iam.Domain.Entities;
using Iam.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace Iam.Features.Services;

/// <summary>
/// Loads Countries / Provinces / Districts from the JSON files shipped next
/// to the host binary (SeedData/*.json) on first startup. Idempotent: if the
/// table already has rows, the entity is skipped. Bulk insert is used for
/// Provinces and Districts, which are ~3.5k and ~47k rows respectively.
/// </summary>
public sealed class GeographySeeder(
    IamDbContext db,
    IHostEnvironment env,
    ILogger<GeographySeeder> logger)
{
    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    public async Task SeedAsync(CancellationToken ct = default)
    {
        await SeedCountriesAsync(ct);
        await SeedProvincesAsync(ct);
        await SeedDistrictsAsync(ct);
    }

    private async Task SeedCountriesAsync(CancellationToken ct)
    {
        if (await db.Countries.AnyAsync(ct))
        {
            return;
        }

        var path = Path.Combine(env.ContentRootPath, "SeedData", "countries.json");
        var countries = await LoadAsync<List<CountrySeedRow>>(path, ct);
        if (countries is null || countries.Count == 0)
        {
            logger.LogWarning("Country seed file missing or empty: {Path}", path);
            return;
        }

        foreach (var c in countries)
        {
            db.Countries.Add(new Country
            {
                Id = c.Id,
                Name = c.Name,
                Code = c.Code,
                Code3 = c.Code3,
                NumericCode = c.NumericCode,
                NativeName = c.NativeName,
                PhoneCode = c.PhoneCode,
                CurrencyCode = string.IsNullOrWhiteSpace(c.DefaultCurrencyCode) ? "USD" : c.DefaultCurrencyCode,
                CurrencySymbol = c.DefaultCurrencySymbol,
            });
        }

        await db.SaveChangesAsync(ct);

        // Countries.Id is GENERATED BY DEFAULT AS IDENTITY; explicit inserts
        // don't advance the sequence, so any future dynamic insert would
        // collide on id=1. Nudge the sequence past the seeded max.
        await db.Database.ExecuteSqlRawAsync(
            """SELECT setval(pg_get_serial_sequence('"Countries"', 'Id'), COALESCE((SELECT MAX("Id") FROM "Countries"), 1), true);""",
            ct);

        logger.LogInformation("Seeded {Count} countries", countries.Count);
    }

    private async Task SeedProvincesAsync(CancellationToken ct)
    {
        if (await db.Provinces.AnyAsync(ct))
        {
            return;
        }

        var path = Path.Combine(env.ContentRootPath, "SeedData", "provinces.json");
        var provinces = await LoadAsync<List<ProvinceSeedRow>>(path, ct);
        if (provinces is null || provinces.Count == 0)
        {
            logger.LogWarning("Province seed file missing or empty: {Path}", path);
            return;
        }

        db.ChangeTracker.AutoDetectChangesEnabled = false;
        try
        {
            foreach (var p in provinces)
            {
                db.Provinces.Add(new Province
                {
                    Id = p.Id,
                    CountryId = p.CountryId,
                    Name = p.Name,
                    Code = p.Code,
                    NameTranslations = p.NameTranslations,
                    Latitude = p.Latitude,
                    Longitude = p.Longitude,
                    Population = p.Population,
                    Timezone = p.Timezone,
                    GeoNameId = p.GeoNameId,
                    SortOrder = p.SortOrder,
                });
            }
            await db.SaveChangesAsync(ct);
        }
        finally
        {
            db.ChangeTracker.AutoDetectChangesEnabled = true;
        }

        logger.LogInformation("Seeded {Count} provinces", provinces.Count);
    }

    private async Task SeedDistrictsAsync(CancellationToken ct)
    {
        if (await db.Districts.AnyAsync(ct))
        {
            return;
        }

        var path = Path.Combine(env.ContentRootPath, "SeedData", "districts.json");
        var districts = await LoadAsync<List<DistrictSeedRow>>(path, ct);
        if (districts is null || districts.Count == 0)
        {
            logger.LogWarning("District seed file missing or empty: {Path}", path);
            return;
        }

        db.ChangeTracker.AutoDetectChangesEnabled = false;
        try
        {
            const int batchSize = 2000;
            var batch = new List<District>(batchSize);
            foreach (var d in districts)
            {
                batch.Add(new District
                {
                    Id = d.Id,
                    ProvinceId = d.ProvinceId,
                    Name = d.Name,
                    NameTranslations = d.NameTranslations,
                    Latitude = d.Latitude,
                    Longitude = d.Longitude,
                    Population = d.Population,
                    Timezone = d.Timezone,
                    GeoNameId = d.GeoNameId,
                    SortOrder = d.SortOrder,
                });

                if (batch.Count >= batchSize)
                {
                    db.Districts.AddRange(batch);
                    await db.SaveChangesAsync(ct);
                    db.ChangeTracker.Clear();
                    batch.Clear();
                }
            }

            if (batch.Count > 0)
            {
                db.Districts.AddRange(batch);
                await db.SaveChangesAsync(ct);
                db.ChangeTracker.Clear();
            }
        }
        finally
        {
            db.ChangeTracker.AutoDetectChangesEnabled = true;
        }

        logger.LogInformation("Seeded {Count} districts", districts.Count);
    }

    private static async Task<T?> LoadAsync<T>(string path, CancellationToken ct)
    {
        if (!File.Exists(path))
        {
            return default;
        }
        await using var stream = File.OpenRead(path);
        return await JsonSerializer.DeserializeAsync<T>(stream, JsonOpts, ct);
    }

    private sealed record CountrySeedRow(
        int Id,
        string Code,
        string? Code3,
        int? NumericCode,
        string Name,
        string? NativeName,
        string? PhoneCode,
        string? Capital,
        string? Continent,
        string? Region,
        bool IsActive,
        string? DefaultCurrencyCode,
        string? DefaultCurrencySymbol);

    private sealed record ProvinceSeedRow(
        int Id,
        int CountryId,
        string Name,
        string? Code,
        string? NameTranslations,
        double? Latitude,
        double? Longitude,
        long? Population,
        string? Timezone,
        int? GeoNameId,
        int SortOrder);

    private sealed record DistrictSeedRow(
        int Id,
        int ProvinceId,
        string Name,
        string? NameTranslations,
        double? Latitude,
        double? Longitude,
        long? Population,
        string? Timezone,
        int? GeoNameId,
        int SortOrder);
}
