
 @Url= http://localhost:5000
#  @Url=http://3.88.252.189:5000
# @Url= https://api-test.toprak.tkholding.com.tr/koopposbackoffice

  @Jwt =  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5OWQyM2YxZi1kMmVlLTQwYjUtOTRlZS00Yjg4MGRkMjM1NGUiLCJnaXZlbl9uYW1lIjoiQmlsYWwwMTEiLCJ1bmlxdWVfbmFtZSI6IkJpbGFsIEtheWFyIiwiZW1haWwiOiJrYXJhYmV5bGl5aW1AZ21haWwuY29tIiwicHJvZmlsZVVybCI6IiIsInRlbmFudElkIjoiYzlkOGM4NDYtMTBmYy00NjZkLThmNDUtYTRmYTRlODU2YWJkIiwicGxhdGZvcm0iOiIwIiwidXNlclNvdXJjZSI6IjAiLCJyZWZyZXNoVG9rZW5JZCI6IjQwMThiMzU2LWEyOGItNDhjYy1iM2YzLWRiZTRjZDUxNzk0YyIsInVzZXJUeXBlIjoiMCIsIm5iZiI6MTc1MDUxOTI0MiwiZXhwIjoxNzUxMTI0MDQyLCJpYXQiOjE3NTA1MTkyNDIsImF1ZCI6ImFwaS5oaXJvdm8uY29tIn0.fEZm1FvitLAW5owbtY91a6-VnopeY-Xaairm9hAbgM"

 
### Create

POST {{Url}}/Jobs/Create  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "title": "Temizlik Elemanı",
  "description": "Haftalık gündüz temizlik işi",
  "salary": 850,
  "type": 1,
  "employerId": "99D23F1F-D2EE-40B5-94EE-4B880DD2354E",
  "latitude": 41.0082,
  "longitude": 28.9784,
  "notifyRadiusKm": 10,
  "companyId": "c9d8c846-10fc-466d-8f45-a4fa4e856abd"
}



### Detail

POST {{Url}}/Jobs/Detail  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "jobId": "07abc2af-6ebe-4a62-b439-752bfd5bca5e"
}



### All

POST {{Url}}/Jobs/All  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "languageCode": "tr-TR",
  "Sorting": null,
  "filters": [
    {
      "key": "hirovoEmployer_Id",     
      "type": "guid",                  
      "isUsed": true,
      "values": ["64733F75-840D-4219-9E77-543445E08022"],
      "conditionType": "equals",
      "max": false,
      "min": false
    }
  ],
  "PageRequest": {
    "PerPageCount": 20,
    "CurrentPage": 1,
    "ListAll": false
  }
}







### Update

POST {{Url}}/Jobs/Update  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "jobId": "2f13e408-fed7-4fd7-ac81-1616b3655de8",
  "title": "Depo Elemanı (Güncellenmiş)",
  "description": "Vardiyalı çalışacak personel aranıyor.",
  "salary": 700,
  "type": 1,
  "status": 1
}


### Delete (soft delete)

POST {{Url}}/Jobs/Delete  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "jobId": "2f13e408-fed7-4fd7-ac81-1616b3655de8",
  "isDeleted": true
}


### Pick

POST {{Url}}/Jobs/Pick  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "selectedIds": [],
  "keyword": "temizlik",
  "limit": 10
}
