
 @Url= http://localhost:5000
#  @Url=http://3.88.252.189:5000
# @Url= https://api-test.toprak.tkholding.com.tr/koopposbackoffice

  @Jwt =  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5OWQyM2YxZi1kMmVlLTQwYjUtOTRlZS00Yjg4MGRkMjM1NGUiLCJnaXZlbl9uYW1lIjoiQmlsYWwwMTEiLCJ1bmlxdWVfbmFtZSI6IkJpbGFsIEtheWFyIiwiZW1haWwiOiJrYXJhYmV5bGl5aW1AZ21haWwuY29tIiwicHJvZmlsZVVybCI6IiIsInRlbmFudElkIjoiYzlkOGM4NDYtMTBmYy00NjZkLThmNDUtYTRmYTRlODU2YWJkIiwicGxhdGZvcm0iOiIwIiwidXNlclNvdXJjZSI6IjAiLCJyZWZyZXNoVG9rZW5JZCI6IjQwMThiMzU2LWEyOGItNDhjYy1iM2YzLWRiZTRjZDUxNzk0YyIsInVzZXJUeXBlIjoiMCIsIm5iZiI6MTc1MDUxOTI0MiwiZXhwIjoxNzUxMTI0MDQyLCJpYXQiOjE3NTA1MTkyNDIsImF1ZCI6ImFwaS5oaXJvdm8uY29tIn0.fEZm1FvitLAW5owbtY91a6-VnopeY-Xaairm9hAbgM"




 ### İş Başvurusu Oluştur
POST {{Url}}/JobApplications/Create
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "jobId": "2AEABB73-927D-4CA5-8DC2-1C46CEC089D9",
  "workerId": "99D23F1F-D2EE-40B5-94EE-4B880DD2354E",
  "companyId": "C9D8C846-10FC-466D-8F45-A4FA4E856ABD"
}


### Tüm Başvuruları Listele (Pagination destekli)
POST {{Url}}/JobApplications/All
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "sorting": null,
  "filters": [],
  "pageRequest": {
    "perPageCount": 20,
    "currentPage": 1,
    "listAll": false
  }
}


### JobApplication Detayı Getir
POST {{Url}}/JobApplications/Detail
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "jobApplicationId": "3524597a-02be-4238-a214-b68f6f289814",
  "companyId": "C9D8C846-10FC-466D-8F45-A4FA4E856ABD"
}


### Başvuru Durumu Güncelle
POST {{Url}}/JobApplications/UpdateStatus
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "jobApplicationId": "3524597a-02be-4238-a214-b68f6f289814",
  "status": 2,
  "companyId": "C9D8C846-10FC-466D-8F45-A4FA4E856ABD"
}


### Başvuru Sil (Soft Delete)
POST {{Url}}/JobApplications/Delete
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "jobApplicationId": "3524597a-02be-4238-a214-b68f6f289814",
  "companyId": "C9D8C846-10FC-466D-8F45-A4FA4E856ABD"
}



### Pick

POST {{Url}}/JobApplications/Pick
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "selectedIds": [],
  "keyword": "",
  "limit": 5
}


### JobApplications.Commands.Update
POST {{Url}}/JobApplications/Update
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "jobApplicationId": "3524597a-02be-4238-a214-b68f6f289814",
  "jobId": "9CCC0C35-A693-48FA-B538-E4DEF770F769",
  "workerId": "E7ECBE7F-B013-47EF-B47F-88479E6677DF",
  "appliedAt": "2025-05-17T14:00:00Z",
  "companyId": "C9D8C846-10FC-466D-8F45-A4FA4E856ABD"
}


### İşe Alınan İşçi Başvurusu Oluştur
POST {{Url}}/JobApplications/AppliedJobs
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "workerId": "d92e02da-606b-4fc4-a3a4-dbcbe2e04af2"
}
