
 @Url= http://localhost:5000
#  @Url=http://3.88.252.189:5000
# @Url= https://api-test.toprak.tkholding.com.tr/koopposbackoffice

  @Jwt =  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkOTJlMDJkYS02MDZiLTRmYzQtYTNhNC1kYmNiZTJlMDRhZjIiLCJnaXZlbl9uYW1lIjoibW9jYWsiLCJ1bmlxdWVfbmFtZSI6Ik11c3RhZmEgT2NhayIsInRlbmFudElkIjoiYzlkOGM4NDYtMTBmYy00NjZkLThmNDUtYTRmYTRlODU2YWJkIiwicGxhdGZvcm0iOiIwIiwidXNlclNvdXJjZSI6IjAiLCJyZWZyZXNoVG9rZW5JZCI6IjIwMzBhYzIyLTYxYmYtNDAyOS04M2ZiLWJjMTIwY2QwMmEwZSIsInVzZXJUeXBlIjoiMSIsIm5iZiI6MTc1MDI3ODUyMCwiZXhwIjoxNzUwODgzMzIwLCJpYXQiOjE3NTAyNzg1MjAsImF1ZCI6ImFwaS5oaXJvdm8uY29tIn0.vIhVzGfjflcV0_djIWl72x4USSr7kGG5mnVGTP8BkLg"

 
### SET LOCATION - Abdullah Karotçu (Manual kayıtlı)
POST {{Url}}/hirovo/Location/SetLocation
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "userId": "3697bcd7-910a-43d5-9976-0eaedf4e077b",
  "companyId": "C9D8C846-10FC-466D-8F45-A4FA4E856ABD",
  "latitude": 40.9104817,
  "longitude": 29.2977463
}



### GET NEARBY WORKERS
POST {{Url}}/hirovo/Location/GetNearbyWorkers
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "companyId": "C9D8C846-10FC-466D-8F45-A4FA4E856ABD", 
  "latitude": 39.8208,
  "longitude": 32.8541,
  "limit": 10
}


### GET NEARBY EMPLOYERS
POST {{Url}}/Location/GetNearbyJobs
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "latitude": 40.991,
  "longitude": 29.123,
  "companyId": "c9d8c846-10fc-466d-8f45-a4fa4e856abd",
  "limit": 10
}
