
 @Url= http://localhost:5000
#  @Url=http://3.88.252.189:5000
# @Url= https://api-test.toprak.tkholding.com.tr/koopposbackoffice

  @Jwt =  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5OWQyM2YxZi1kMmVlLTQwYjUtOTRlZS00Yjg4MGRkMjM1NGUiLCJnaXZlbl9uYW1lIjoiQmlsYWwwMTEiLCJ1bmlxdWVfbmFtZSI6IkJpbGFsIEtheWFyIiwiZW1haWwiOiJrYXJhYmV5bGl5aW1AZ21haWwuY29tIiwicHJvZmlsZVVybCI6IiIsInRlbmFudElkIjoiYzlkOGM4NDYtMTBmYy00NjZkLThmNDUtYTRmYTRlODU2YWJkIiwicGxhdGZvcm0iOiIwIiwidXNlclNvdXJjZSI6IjAiLCJyZWZyZXNoVG9rZW5JZCI6IjQwMThiMzU2LWEyOGItNDhjYy1iM2YzLWRiZTRjZDUxNzk0YyIsInVzZXJUeXBlIjoiMCIsIm5iZiI6MTc1MDUxOTI0MiwiZXhwIjoxNzUxMTI0MDQyLCJpYXQiOjE3NTA1MTkyNDIsImF1ZCI6ImFwaS5oaXJvdm8uY29tIn0.fEZm1FvitLAW5owbtY91a6-VnopeY-Xaairm9hAbgM"

 
### Create

POST {{Url}}/Skills/Create  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "key": "gardener",
  "languageCode": "tr",
  "translatedName": "Bahçıvan"
}




### Pick
POST {{Url}}/Skills/Pick  
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json
 
{
  "keyword": "React",
  "selectedIds": [],
  "limit": 5
}


,

### Pick
POST {{Url}}/Skills/SeedAndTranslate  
Accept: application/json
Content-Type: application/json
 
{
}
