-- Seed Countries Data (ISO 3166-1)
-- Bu script ilk migration'da çalıştırılmalıdır

IF NOT EXISTS (SELECT 1 FROM Countries WHERE Id = 1)
BEGIN
    SET IDENTITY_INSERT [Countries] ON;

    INSERT INTO [Countries] ([Id], [Code], [Code3], [NumericCode], [Name], [NativeName], [PhoneCode], [Capital], [Continent], [Region], [IsActive])
    VALUES
    (1, 'AF', 'AFG', 4, 'Afghanistan', N'افغانستان', '93', 'Kabul', 'Asia', 'Southern Asia', 1),
    (2, 'AL', 'ALB', 8, 'Albania', N'Shqipëria', '355', 'Tirana', 'Europe', 'Southern Europe', 1),
    (3, 'DZ', 'DZA', 12, 'Algeria', N'الجزائر', '213', 'Algiers', 'Africa', 'Northern Africa', 1),
    (4, 'AD', 'AND', 20, 'Andorra', N'Andorra', '376', 'Andorra la Vella', 'Europe', 'Southern Europe', 1),
    (5, 'AO', 'AGO', 24, 'Angola', N'Angola', '244', 'Luanda', 'Africa', 'Middle Africa', 1),
    (6, 'AG', 'ATG', 28, 'Antigua and Barbuda', N'Antigua and Barbuda', '1-268', 'Saint John''s', 'North America', 'Caribbean', 1),
    (7, 'AR', 'ARG', 32, 'Argentina', N'Argentina', '54', 'Buenos Aires', 'South America', 'South America', 1),
    (8, 'AM', 'ARM', 51, 'Armenia', N'Հdelays', '374', 'Yerevan', 'Asia', 'Western Asia', 1),
    (9, 'AU', 'AUS', 36, 'Australia', N'Australia', '61', 'Canberra', 'Oceania', 'Australia and New Zealand', 1),
    (10, 'AT', 'AUT', 40, 'Austria', N'Österreich', '43', 'Vienna', 'Europe', 'Western Europe', 1),
    (11, 'AZ', 'AZE', 31, 'Azerbaijan', N'Azərbaycan', '994', 'Baku', 'Asia', 'Western Asia', 1),
    (12, 'BS', 'BHS', 44, 'Bahamas', N'Bahamas', '1-242', 'Nassau', 'North America', 'Caribbean', 1),
    (13, 'BH', 'BHR', 48, 'Bahrain', N'البحرين', '973', 'Manama', 'Asia', 'Western Asia', 1),
    (14, 'BD', 'BGD', 50, 'Bangladesh', N'বাংলাদেশ', '880', 'Dhaka', 'Asia', 'Southern Asia', 1),
    (15, 'BB', 'BRB', 52, 'Barbados', N'Barbados', '1-246', 'Bridgetown', 'North America', 'Caribbean', 1),
    (16, 'BY', 'BLR', 112, 'Belarus', N'Беларусь', '375', 'Minsk', 'Europe', 'Eastern Europe', 1),
    (17, 'BE', 'BEL', 56, 'Belgium', N'België', '32', 'Brussels', 'Europe', 'Western Europe', 1),
    (18, 'BZ', 'BLZ', 84, 'Belize', N'Belize', '501', 'Belmopan', 'North America', 'Central America', 1),
    (19, 'BJ', 'BEN', 204, 'Benin', N'Bénin', '229', 'Porto-Novo', 'Africa', 'Western Africa', 1),
    (20, 'BT', 'BTN', 64, 'Bhutan', N'འབྲུག', '975', 'Thimphu', 'Asia', 'Southern Asia', 1),
    (21, 'BO', 'BOL', 68, 'Bolivia', N'Bolivia', '591', 'Sucre', 'South America', 'South America', 1),
    (22, 'BA', 'BIH', 70, 'Bosnia and Herzegovina', N'Bosna i Hercegovina', '387', 'Sarajevo', 'Europe', 'Southern Europe', 1),
    (23, 'BW', 'BWA', 72, 'Botswana', N'Botswana', '267', 'Gaborone', 'Africa', 'Southern Africa', 1),
    (24, 'BR', 'BRA', 76, 'Brazil', N'Brasil', '55', 'Brasília', 'South America', 'South America', 1),
    (25, 'BN', 'BRN', 96, 'Brunei', N'Brunei', '673', 'Bandar Seri Begawan', 'Asia', 'South-Eastern Asia', 1),
    (26, 'BG', 'BGR', 100, 'Bulgaria', N'България', '359', 'Sofia', 'Europe', 'Eastern Europe', 1),
    (27, 'BF', 'BFA', 854, 'Burkina Faso', N'Burkina Faso', '226', 'Ouagadougou', 'Africa', 'Western Africa', 1),
    (28, 'BI', 'BDI', 108, 'Burundi', N'Burundi', '257', 'Gitega', 'Africa', 'Eastern Africa', 1),
    (29, 'CV', 'CPV', 132, 'Cabo Verde', N'Cabo Verde', '238', 'Praia', 'Africa', 'Western Africa', 1),
    (30, 'KH', 'KHM', 116, 'Cambodia', N'កម្ពុជា', '855', 'Phnom Penh', 'Asia', 'South-Eastern Asia', 1),
    (31, 'CM', 'CMR', 120, 'Cameroon', N'Cameroun', '237', 'Yaoundé', 'Africa', 'Middle Africa', 1),
    (32, 'CA', 'CAN', 124, 'Canada', N'Canada', '1', 'Ottawa', 'North America', 'Northern America', 1),
    (33, 'CF', 'CAF', 140, 'Central African Republic', N'République centrafricaine', '236', 'Bangui', 'Africa', 'Middle Africa', 1),
    (34, 'TD', 'TCD', 148, 'Chad', N'Tchad', '235', 'N''Djamena', 'Africa', 'Middle Africa', 1),
    (35, 'CL', 'CHL', 152, 'Chile', N'Chile', '56', 'Santiago', 'South America', 'South America', 1),
    (36, 'CN', 'CHN', 156, 'China', N'中国', '86', 'Beijing', 'Asia', 'Eastern Asia', 1),
    (37, 'CO', 'COL', 170, 'Colombia', N'Colombia', '57', 'Bogotá', 'South America', 'South America', 1),
    (38, 'KM', 'COM', 174, 'Comoros', N'جزر القمر', '269', 'Moroni', 'Africa', 'Eastern Africa', 1),
    (39, 'CG', 'COG', 178, 'Congo', N'Congo', '242', 'Brazzaville', 'Africa', 'Middle Africa', 1),
    (40, 'CD', 'COD', 180, 'Congo (Democratic Republic)', N'République démocratique du Congo', '243', 'Kinshasa', 'Africa', 'Middle Africa', 1),
    (41, 'CR', 'CRI', 188, 'Costa Rica', N'Costa Rica', '506', 'San José', 'North America', 'Central America', 1),
    (42, 'HR', 'HRV', 191, 'Croatia', N'Hrvatska', '385', 'Zagreb', 'Europe', 'Southern Europe', 1),
    (43, 'CU', 'CUB', 192, 'Cuba', N'Cuba', '53', 'Havana', 'North America', 'Caribbean', 1),
    (44, 'CY', 'CYP', 196, 'Cyprus', N'Κύπρος', '357', 'Nicosia', 'Europe', 'Western Asia', 1),
    (45, 'CZ', 'CZE', 203, 'Czechia', N'Česko', '420', 'Prague', 'Europe', 'Eastern Europe', 1),
    (46, 'CI', 'CIV', 384, 'Côte d''Ivoire', N'Côte d''Ivoire', '225', 'Yamoussoukro', 'Africa', 'Western Africa', 1),
    (47, 'DK', 'DNK', 208, 'Denmark', N'Danmark', '45', 'Copenhagen', 'Europe', 'Northern Europe', 1),
    (48, 'DJ', 'DJI', 262, 'Djibouti', N'Djibouti', '253', 'Djibouti', 'Africa', 'Eastern Africa', 1),
    (49, 'DM', 'DMA', 212, 'Dominica', N'Dominica', '1-767', 'Roseau', 'North America', 'Caribbean', 1),
    (50, 'DO', 'DOM', 214, 'Dominican Republic', N'República Dominicana', '1-809', 'Santo Domingo', 'North America', 'Caribbean', 1),
    (51, 'EC', 'ECU', 218, 'Ecuador', N'Ecuador', '593', 'Quito', 'South America', 'South America', 1),
    (52, 'EG', 'EGY', 818, 'Egypt', N'مصر', '20', 'Cairo', 'Africa', 'Northern Africa', 1),
    (53, 'SV', 'SLV', 222, 'El Salvador', N'El Salvador', '503', 'San Salvador', 'North America', 'Central America', 1),
    (54, 'GQ', 'GNQ', 226, 'Equatorial Guinea', N'Guinea Ecuatorial', '240', 'Malabo', 'Africa', 'Middle Africa', 1),
    (55, 'ER', 'ERI', 232, 'Eritrea', N'ኤርትራ', '291', 'Asmara', 'Africa', 'Eastern Africa', 1),
    (56, 'EE', 'EST', 233, 'Estonia', N'Eesti', '372', 'Tallinn', 'Europe', 'Northern Europe', 1),
    (57, 'SZ', 'SWZ', 748, 'Eswatini', N'Eswatini', '268', 'Mbabane', 'Africa', 'Southern Africa', 1),
    (58, 'ET', 'ETH', 231, 'Ethiopia', N'ኢትዮጵያ', '251', 'Addis Ababa', 'Africa', 'Eastern Africa', 1),
    (59, 'FJ', 'FJI', 242, 'Fiji', N'Fiji', '679', 'Suva', 'Oceania', 'Melanesia', 1),
    (60, 'FI', 'FIN', 246, 'Finland', N'Suomi', '358', 'Helsinki', 'Europe', 'Northern Europe', 1),
    (61, 'FR', 'FRA', 250, 'France', N'France', '33', 'Paris', 'Europe', 'Western Europe', 1),
    (62, 'GA', 'GAB', 266, 'Gabon', N'Gabon', '241', 'Libreville', 'Africa', 'Middle Africa', 1),
    (63, 'GM', 'GMB', 270, 'Gambia', N'Gambia', '220', 'Banjul', 'Africa', 'Western Africa', 1),
    (64, 'GE', 'GEO', 268, 'Georgia', N'საქართველო', '995', 'Tbilisi', 'Asia', 'Western Asia', 1),
    (65, 'DE', 'DEU', 276, 'Germany', N'Deutschland', '49', 'Berlin', 'Europe', 'Western Europe', 1),
    (66, 'GH', 'GHA', 288, 'Ghana', N'Ghana', '233', 'Accra', 'Africa', 'Western Africa', 1),
    (67, 'GR', 'GRC', 300, 'Greece', N'Ελλάδα', '30', 'Athens', 'Europe', 'Southern Europe', 1),
    (68, 'GD', 'GRD', 308, 'Grenada', N'Grenada', '1-473', 'St. George''s', 'North America', 'Caribbean', 1),
    (69, 'GT', 'GTM', 320, 'Guatemala', N'Guatemala', '502', 'Guatemala City', 'North America', 'Central America', 1),
    (70, 'GN', 'GIN', 324, 'Guinea', N'Guinée', '224', 'Conakry', 'Africa', 'Western Africa', 1),
    (71, 'GW', 'GNB', 624, 'Guinea-Bissau', N'Guiné-Bissau', '245', 'Bissau', 'Africa', 'Western Africa', 1),
    (72, 'GY', 'GUY', 328, 'Guyana', N'Guyana', '592', 'Georgetown', 'South America', 'South America', 1),
    (73, 'HT', 'HTI', 332, 'Haiti', N'Haïti', '509', 'Port-au-Prince', 'North America', 'Caribbean', 1),
    (74, 'HN', 'HND', 340, 'Honduras', N'Honduras', '504', 'Tegucigalpa', 'North America', 'Central America', 1),
    (75, 'HU', 'HUN', 348, 'Hungary', N'Magyarország', '36', 'Budapest', 'Europe', 'Eastern Europe', 1),
    (76, 'IS', 'ISL', 352, 'Iceland', N'Ísland', '354', 'Reykjavik', 'Europe', 'Northern Europe', 1),
    (77, 'IN', 'IND', 356, 'India', N'भारत', '91', 'New Delhi', 'Asia', 'Southern Asia', 1),
    (78, 'ID', 'IDN', 360, 'Indonesia', N'Indonesia', '62', 'Jakarta', 'Asia', 'South-Eastern Asia', 1),
    (79, 'IR', 'IRN', 364, 'Iran', N'ایران', '98', 'Tehran', 'Asia', 'Southern Asia', 1),
    (80, 'IQ', 'IRQ', 368, 'Iraq', N'العراق', '964', 'Baghdad', 'Asia', 'Western Asia', 1),
    (81, 'IE', 'IRL', 372, 'Ireland', N'Éire', '353', 'Dublin', 'Europe', 'Northern Europe', 1),
    (82, 'IL', 'ISR', 376, 'Israel', N'ישראל', '972', 'Jerusalem', 'Asia', 'Western Asia', 1),
    (83, 'IT', 'ITA', 380, 'Italy', N'Italia', '39', 'Rome', 'Europe', 'Southern Europe', 1),
    (84, 'JM', 'JAM', 388, 'Jamaica', N'Jamaica', '1-876', 'Kingston', 'North America', 'Caribbean', 1),
    (85, 'JP', 'JPN', 392, 'Japan', N'日本', '81', 'Tokyo', 'Asia', 'Eastern Asia', 1),
    (86, 'JO', 'JOR', 400, 'Jordan', N'الأردن', '962', 'Amman', 'Asia', 'Western Asia', 1),
    (87, 'KZ', 'KAZ', 398, 'Kazakhstan', N'Қазақстан', '7', 'Astana', 'Asia', 'Central Asia', 1),
    (88, 'KE', 'KEN', 404, 'Kenya', N'Kenya', '254', 'Nairobi', 'Africa', 'Eastern Africa', 1),
    (89, 'KI', 'KIR', 296, 'Kiribati', N'Kiribati', '686', 'Tarawa', 'Oceania', 'Micronesia', 1),
    (90, 'KP', 'PRK', 408, 'Korea (North)', N'조선', '850', 'Pyongyang', 'Asia', 'Eastern Asia', 1),
    (91, 'KR', 'KOR', 410, 'Korea (South)', N'대한민국', '82', 'Seoul', 'Asia', 'Eastern Asia', 1),
    (92, 'KW', 'KWT', 414, 'Kuwait', N'الكويت', '965', 'Kuwait City', 'Asia', 'Western Asia', 1),
    (93, 'KG', 'KGZ', 417, 'Kyrgyzstan', N'Кыргызстан', '996', 'Bishkek', 'Asia', 'Central Asia', 1),
    (94, 'LA', 'LAO', 418, 'Laos', N'ລາວ', '856', 'Vientiane', 'Asia', 'South-Eastern Asia', 1),
    (95, 'LV', 'LVA', 428, 'Latvia', N'Latvija', '371', 'Riga', 'Europe', 'Northern Europe', 1),
    (96, 'LB', 'LBN', 422, 'Lebanon', N'لبنان', '961', 'Beirut', 'Asia', 'Western Asia', 1),
    (97, 'LS', 'LSO', 426, 'Lesotho', N'Lesotho', '266', 'Maseru', 'Africa', 'Southern Africa', 1),
    (98, 'LR', 'LBR', 430, 'Liberia', N'Liberia', '231', 'Monrovia', 'Africa', 'Western Africa', 1),
    (99, 'LY', 'LBY', 434, 'Libya', N'ليبيا', '218', 'Tripoli', 'Africa', 'Northern Africa', 1),
    (100, 'LI', 'LIE', 438, 'Liechtenstein', N'Liechtenstein', '423', 'Vaduz', 'Europe', 'Western Europe', 1),
    (101, 'LT', 'LTU', 440, 'Lithuania', N'Lietuva', '370', 'Vilnius', 'Europe', 'Northern Europe', 1),
    (102, 'LU', 'LUX', 442, 'Luxembourg', N'Luxembourg', '352', 'Luxembourg', 'Europe', 'Western Europe', 1),
    (103, 'MG', 'MDG', 450, 'Madagascar', N'Madagasikara', '261', 'Antananarivo', 'Africa', 'Eastern Africa', 1),
    (104, 'MW', 'MWI', 454, 'Malawi', N'Malawi', '265', 'Lilongwe', 'Africa', 'Eastern Africa', 1),
    (105, 'MY', 'MYS', 458, 'Malaysia', N'Malaysia', '60', 'Kuala Lumpur', 'Asia', 'South-Eastern Asia', 1),
    (106, 'MV', 'MDV', 462, 'Maldives', N'ދިވެހިރާއްޖެ', '960', 'Malé', 'Asia', 'Southern Asia', 1),
    (107, 'ML', 'MLI', 466, 'Mali', N'Mali', '223', 'Bamako', 'Africa', 'Western Africa', 1),
    (108, 'MT', 'MLT', 470, 'Malta', N'Malta', '356', 'Valletta', 'Europe', 'Southern Europe', 1),
    (109, 'MH', 'MHL', 584, 'Marshall Islands', N'Marshall Islands', '692', 'Majuro', 'Oceania', 'Micronesia', 1),
    (110, 'MR', 'MRT', 478, 'Mauritania', N'موريتانيا', '222', 'Nouakchott', 'Africa', 'Western Africa', 1),
    (111, 'MU', 'MUS', 480, 'Mauritius', N'Maurice', '230', 'Port Louis', 'Africa', 'Eastern Africa', 1),
    (112, 'MX', 'MEX', 484, 'Mexico', N'México', '52', 'Mexico City', 'North America', 'Central America', 1),
    (113, 'FM', 'FSM', 583, 'Micronesia', N'Micronesia', '691', 'Palikir', 'Oceania', 'Micronesia', 1),
    (114, 'MD', 'MDA', 498, 'Moldova', N'Moldova', '373', 'Chișinău', 'Europe', 'Eastern Europe', 1),
    (115, 'MC', 'MCO', 492, 'Monaco', N'Monaco', '377', 'Monaco', 'Europe', 'Western Europe', 1),
    (116, 'MN', 'MNG', 496, 'Mongolia', N'Монгол улс', '976', 'Ulaanbaatar', 'Asia', 'Eastern Asia', 1),
    (117, 'ME', 'MNE', 499, 'Montenegro', N'Crna Gora', '382', 'Podgorica', 'Europe', 'Southern Europe', 1),
    (118, 'MA', 'MAR', 504, 'Morocco', N'المغرب', '212', 'Rabat', 'Africa', 'Northern Africa', 1),
    (119, 'MZ', 'MOZ', 508, 'Mozambique', N'Moçambique', '258', 'Maputo', 'Africa', 'Eastern Africa', 1),
    (120, 'MM', 'MMR', 104, 'Myanmar', N'မြန်မာ', '95', 'Naypyidaw', 'Asia', 'South-Eastern Asia', 1),
    (121, 'NA', 'NAM', 516, 'Namibia', N'Namibia', '264', 'Windhoek', 'Africa', 'Southern Africa', 1),
    (122, 'NR', 'NRU', 520, 'Nauru', N'Nauru', '674', 'Yaren', 'Oceania', 'Micronesia', 1),
    (123, 'NP', 'NPL', 524, 'Nepal', N'नेपाल', '977', 'Kathmandu', 'Asia', 'Southern Asia', 1),
    (124, 'NL', 'NLD', 528, 'Netherlands', N'Nederland', '31', 'Amsterdam', 'Europe', 'Western Europe', 1),
    (125, 'NZ', 'NZL', 554, 'New Zealand', N'New Zealand', '64', 'Wellington', 'Oceania', 'Australia and New Zealand', 1),
    (126, 'NI', 'NIC', 558, 'Nicaragua', N'Nicaragua', '505', 'Managua', 'North America', 'Central America', 1),
    (127, 'NE', 'NER', 562, 'Niger', N'Niger', '227', 'Niamey', 'Africa', 'Western Africa', 1),
    (128, 'NG', 'NGA', 566, 'Nigeria', N'Nigeria', '234', 'Abuja', 'Africa', 'Western Africa', 1),
    (129, 'MK', 'MKD', 807, 'North Macedonia', N'Северна Македонија', '389', 'Skopje', 'Europe', 'Southern Europe', 1),
    (130, 'NO', 'NOR', 578, 'Norway', N'Norge', '47', 'Oslo', 'Europe', 'Northern Europe', 1),
    (131, 'OM', 'OMN', 512, 'Oman', N'عمان', '968', 'Muscat', 'Asia', 'Western Asia', 1),
    (132, 'PK', 'PAK', 586, 'Pakistan', N'پاکستان', '92', 'Islamabad', 'Asia', 'Southern Asia', 1),
    (133, 'PW', 'PLW', 585, 'Palau', N'Palau', '680', 'Ngerulmud', 'Oceania', 'Micronesia', 1),
    (134, 'PS', 'PSE', 275, 'Palestine', N'فلسطين', '970', 'Ramallah', 'Asia', 'Western Asia', 1),
    (135, 'PA', 'PAN', 591, 'Panama', N'Panamá', '507', 'Panama City', 'North America', 'Central America', 1),
    (136, 'PG', 'PNG', 598, 'Papua New Guinea', N'Papua New Guinea', '675', 'Port Moresby', 'Oceania', 'Melanesia', 1),
    (137, 'PY', 'PRY', 600, 'Paraguay', N'Paraguay', '595', 'Asunción', 'South America', 'South America', 1),
    (138, 'PE', 'PER', 604, 'Peru', N'Perú', '51', 'Lima', 'South America', 'South America', 1),
    (139, 'PH', 'PHL', 608, 'Philippines', N'Pilipinas', '63', 'Manila', 'Asia', 'South-Eastern Asia', 1),
    (140, 'PL', 'POL', 616, 'Poland', N'Polska', '48', 'Warsaw', 'Europe', 'Eastern Europe', 1),
    (141, 'PT', 'PRT', 620, 'Portugal', N'Portugal', '351', 'Lisbon', 'Europe', 'Southern Europe', 1),
    (142, 'QA', 'QAT', 634, 'Qatar', N'قطر', '974', 'Doha', 'Asia', 'Western Asia', 1),
    (143, 'RO', 'ROU', 642, 'Romania', N'România', '40', 'Bucharest', 'Europe', 'Eastern Europe', 1),
    (144, 'RU', 'RUS', 643, 'Russia', N'Россия', '7', 'Moscow', 'Europe', 'Eastern Europe', 1),
    (145, 'RW', 'RWA', 646, 'Rwanda', N'Rwanda', '250', 'Kigali', 'Africa', 'Eastern Africa', 1),
    (146, 'KN', 'KNA', 659, 'Saint Kitts and Nevis', N'Saint Kitts and Nevis', '1-869', 'Basseterre', 'North America', 'Caribbean', 1),
    (147, 'LC', 'LCA', 662, 'Saint Lucia', N'Saint Lucia', '1-758', 'Castries', 'North America', 'Caribbean', 1),
    (148, 'VC', 'VCT', 670, 'Saint Vincent and the Grenadines', N'Saint Vincent and the Grenadines', '1-784', 'Kingstown', 'North America', 'Caribbean', 1),
    (149, 'WS', 'WSM', 882, 'Samoa', N'Samoa', '685', 'Apia', 'Oceania', 'Polynesia', 1),
    (150, 'SM', 'SMR', 674, 'San Marino', N'San Marino', '378', 'San Marino', 'Europe', 'Southern Europe', 1),
    (151, 'ST', 'STP', 678, 'Sao Tome and Principe', N'São Tomé e Príncipe', '239', 'São Tomé', 'Africa', 'Middle Africa', 1),
    (152, 'SA', 'SAU', 682, 'Saudi Arabia', N'السعودية', '966', 'Riyadh', 'Asia', 'Western Asia', 1),
    (153, 'SN', 'SEN', 686, 'Senegal', N'Sénégal', '221', 'Dakar', 'Africa', 'Western Africa', 1),
    (154, 'RS', 'SRB', 688, 'Serbia', N'Србија', '381', 'Belgrade', 'Europe', 'Southern Europe', 1),
    (155, 'SC', 'SYC', 690, 'Seychelles', N'Seychelles', '248', 'Victoria', 'Africa', 'Eastern Africa', 1),
    (156, 'SL', 'SLE', 694, 'Sierra Leone', N'Sierra Leone', '232', 'Freetown', 'Africa', 'Western Africa', 1),
    (157, 'SG', 'SGP', 702, 'Singapore', N'Singapore', '65', 'Singapore', 'Asia', 'South-Eastern Asia', 1),
    (158, 'SK', 'SVK', 703, 'Slovakia', N'Slovensko', '421', 'Bratislava', 'Europe', 'Eastern Europe', 1),
    (159, 'SI', 'SVN', 705, 'Slovenia', N'Slovenija', '386', 'Ljubljana', 'Europe', 'Southern Europe', 1),
    (160, 'SB', 'SLB', 90, 'Solomon Islands', N'Solomon Islands', '677', 'Honiara', 'Oceania', 'Melanesia', 1),
    (161, 'SO', 'SOM', 706, 'Somalia', N'Soomaaliya', '252', 'Mogadishu', 'Africa', 'Eastern Africa', 1),
    (162, 'ZA', 'ZAF', 710, 'South Africa', N'South Africa', '27', 'Pretoria', 'Africa', 'Southern Africa', 1),
    (163, 'SS', 'SSD', 728, 'South Sudan', N'South Sudan', '211', 'Juba', 'Africa', 'Eastern Africa', 1),
    (164, 'ES', 'ESP', 724, 'Spain', N'España', '34', 'Madrid', 'Europe', 'Southern Europe', 1),
    (165, 'LK', 'LKA', 144, 'Sri Lanka', N'ශ්‍රී ලංකාව', '94', 'Sri Jayawardenepura Kotte', 'Asia', 'Southern Asia', 1),
    (166, 'SD', 'SDN', 729, 'Sudan', N'السودان', '249', 'Khartoum', 'Africa', 'Northern Africa', 1),
    (167, 'SR', 'SUR', 740, 'Suriname', N'Suriname', '597', 'Paramaribo', 'South America', 'South America', 1),
    (168, 'SE', 'SWE', 752, 'Sweden', N'Sverige', '46', 'Stockholm', 'Europe', 'Northern Europe', 1),
    (169, 'CH', 'CHE', 756, 'Switzerland', N'Schweiz', '41', 'Bern', 'Europe', 'Western Europe', 1),
    (170, 'SY', 'SYR', 760, 'Syria', N'سوريا', '963', 'Damascus', 'Asia', 'Western Asia', 1),
    (171, 'TW', 'TWN', 158, 'Taiwan', N'臺灣', '886', 'Taipei', 'Asia', 'Eastern Asia', 1),
    (172, 'TJ', 'TJK', 762, 'Tajikistan', N'Тоҷикистон', '992', 'Dushanbe', 'Asia', 'Central Asia', 1),
    (173, 'TZ', 'TZA', 834, 'Tanzania', N'Tanzania', '255', 'Dodoma', 'Africa', 'Eastern Africa', 1),
    (174, 'TH', 'THA', 764, 'Thailand', N'ประเทศไทย', '66', 'Bangkok', 'Asia', 'South-Eastern Asia', 1),
    (175, 'TL', 'TLS', 626, 'Timor-Leste', N'Timor-Leste', '670', 'Dili', 'Asia', 'South-Eastern Asia', 1),
    (176, 'TG', 'TGO', 768, 'Togo', N'Togo', '228', 'Lomé', 'Africa', 'Western Africa', 1),
    (177, 'TO', 'TON', 776, 'Tonga', N'Tonga', '676', 'Nuku''alofa', 'Oceania', 'Polynesia', 1),
    (178, 'TT', 'TTO', 780, 'Trinidad and Tobago', N'Trinidad and Tobago', '1-868', 'Port of Spain', 'North America', 'Caribbean', 1),
    (179, 'TN', 'TUN', 788, 'Tunisia', N'تونس', '216', 'Tunis', 'Africa', 'Northern Africa', 1),
    (180, 'TR', 'TUR', 792, 'Turkey', N'Türkiye', '90', 'Ankara', 'Asia', 'Western Asia', 1),
    (181, 'TM', 'TKM', 795, 'Turkmenistan', N'Türkmenistan', '993', 'Ashgabat', 'Asia', 'Central Asia', 1),
    (182, 'TV', 'TUV', 798, 'Tuvalu', N'Tuvalu', '688', 'Funafuti', 'Oceania', 'Polynesia', 1),
    (183, 'UG', 'UGA', 800, 'Uganda', N'Uganda', '256', 'Kampala', 'Africa', 'Eastern Africa', 1),
    (184, 'UA', 'UKR', 804, 'Ukraine', N'Україна', '380', 'Kyiv', 'Europe', 'Eastern Europe', 1),
    (185, 'AE', 'ARE', 784, 'United Arab Emirates', N'الإمارات العربية المتحدة', '971', 'Abu Dhabi', 'Asia', 'Western Asia', 1),
    (186, 'GB', 'GBR', 826, 'United Kingdom', N'United Kingdom', '44', 'London', 'Europe', 'Northern Europe', 1),
    (187, 'US', 'USA', 840, 'United States', N'United States', '1', 'Washington, D.C.', 'North America', 'Northern America', 1),
    (188, 'UY', 'URY', 858, 'Uruguay', N'Uruguay', '598', 'Montevideo', 'South America', 'South America', 1),
    (189, 'UZ', 'UZB', 860, 'Uzbekistan', N'Oʻzbekiston', '998', 'Tashkent', 'Asia', 'Central Asia', 1),
    (190, 'VU', 'VUT', 548, 'Vanuatu', N'Vanuatu', '678', 'Port Vila', 'Oceania', 'Melanesia', 1),
    (191, 'VA', 'VAT', 336, 'Vatican City', N'Città del Vaticano', '379', 'Vatican City', 'Europe', 'Southern Europe', 1),
    (192, 'VE', 'VEN', 862, 'Venezuela', N'Venezuela', '58', 'Caracas', 'South America', 'South America', 1),
    (193, 'VN', 'VNM', 704, 'Vietnam', N'Việt Nam', '84', 'Hanoi', 'Asia', 'South-Eastern Asia', 1),
    (194, 'YE', 'YEM', 887, 'Yemen', N'اليمن', '967', 'Sana''a', 'Asia', 'Western Asia', 1),
    (195, 'ZM', 'ZMB', 894, 'Zambia', N'Zambia', '260', 'Lusaka', 'Africa', 'Eastern Africa', 1),
    (196, 'ZW', 'ZWE', 716, 'Zimbabwe', N'Zimbabwe', '263', 'Harare', 'Africa', 'Eastern Africa', 1);

    SET IDENTITY_INSERT [Countries] OFF;
END
