
 @Url= http://localhost:5000
#  @Url=http://3.88.252.189:5000
# @Url= https://api-test.toprak.tkholding.com.tr/koopposbackoffice

  @Jwt =  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkOTJlMDJkYS02MDZiLTRmYzQtYTNhNC1kYmNiZTJlMDRhZjIiLCJnaXZlbl9uYW1lIjoibW9jYWsiLCJ1bmlxdWVfbmFtZSI6Ik11c3RhZmEgT2NhayIsInRlbmFudElkIjoiYzlkOGM4NDYtMTBmYy00NjZkLThmNDUtYTRmYTRlODU2YWJkIiwicGxhdGZvcm0iOiIwIiwidXNlclNvdXJjZSI6IjAiLCJuYmYiOjE3NDczNDEzNDIsImV4cCI6MTc0Nzk0NjE0MiwiaWF0IjoxNzQ3MzQxMzQyLCJhdWQiOiJhcGkuaGlyb3ZvLmNvbSJ9.x2NG1XRMMNmsqCTZXpBCMe-rVJrxALX8PqQ8piru-0Q"


### Create
POST {{Url}}/Roles/Create
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "id": "d290f1ee-6c54-4b01-90e6-d701748f0851",
  "name": "Admin4",
  "companyId": "C9D8C846-10FC-466D-8F45-A4FA4E856ABD"

}



### Update
POST {{Url}}/Roles/Update
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "id": "A1D5B3E4-8E5A-4B3C-9EF5-D3E5A3B7C1F8",
  "name": "Admin"
}



### Delete
POST {{Url}}/Roles/Delete
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
  "id": "A1D5B3E4-8E5A-4B3C-9EF5-D3E5A3B7C1F8",
  "isDeleted": false
}



### Delete
POST {{Url}}/Roles/All
Authorization: Bearer {{Jwt}}
Accept: application/json
Content-Type: application/json

{
    "sorting": null,
    "filters": [],
    "pageRequest": {
        "perPageCount": 20,
        "currentPage": 1,
        "listAll": false
    }
}


