###############################################################################
# AUTH ENDPOINTS - IAM Module
# livestock-trading.com
###############################################################################

@BaseUrl = http://localhost:5000


###############################################################################
# 1. KAYIT OL (Register)
###############################################################################
### Yeni Kullanici Olustur
POST {{BaseUrl}}/Users/Create
Accept: application/json
Content-Type: application/json

{
    "userName": "test@example.com",
    "firstName": "Ahmet",
    "surname": "Yilmaz",
    "email": "test@example.com",
    "password": "Test123!",
    "countryId": 792
}


###############################################################################
# 2. GIRIS YAP (Login)
###############################################################################
### Email ve Sifre ile Giris
POST {{BaseUrl}}/Auth/Login
Accept: application/json
Content-Type: application/json

{
    "provider": "native",
    "userName": "test@example.com",
    "password": "Test123!",
    "platform": 0
}
