@BaseUrl = http://localhost:5221

### Create
POST {{BaseUrl}}/ChemicalInfos/Create
Content-Type: application/json

{
    "productId": "00000000-0000-0000-0000-000000000001",
    "type": 0,
    "subType": "Herbicide",
    "activeIngredients": "[\"Glyphosate 360g/L\", \"Surfactant\"]",
    "chemicalFormula": "C3H8NO5P",
    "registrationNumber": "CHEM-REG-2024-0123",
    "toxicityLevel": 0,
    "isOrganic": false
}

### All
POST {{BaseUrl}}/ChemicalInfos/All
Content-Type: application/json

{
    "sorting": null,
    "filters": [],
    "pageRequest": { "page": 1, "pageSize": 10 }
}

### Detail
POST {{BaseUrl}}/ChemicalInfos/Detail
Content-Type: application/json

{
    "id": "00000000-0000-0000-0000-000000000000"
}

### Pick
POST {{BaseUrl}}/ChemicalInfos/Pick
Content-Type: application/json

{
    "selectedIds": [],
    "keyword": "",
    "limit": 10
}

### Update
POST {{BaseUrl}}/ChemicalInfos/Update
Content-Type: application/json

{
    "id": "00000000-0000-0000-0000-000000000000",
    "productId": "00000000-0000-0000-0000-000000000001",
    "type": 0,
    "subType": "Insecticide",
    "activeIngredients": "[\"Cypermethrin 100g/L\"]",
    "chemicalFormula": "C22H19Cl2NO3",
    "registrationNumber": "CHEM-REG-2024-0124",
    "toxicityLevel": 0,
    "isOrganic": false
}

### Delete
POST {{BaseUrl}}/ChemicalInfos/Delete
Content-Type: application/json

{
    "id": "00000000-0000-0000-0000-000000000000"
}
